"""
generate_toda.py
----------------
Generate a periodic Toda lattice benchmark.

Hamiltonian:
    H(q,p) = 0.5 * sum_j p_j^2 + sum_j exp(q_j - q_{j+1})

The periodic Toda lattice is conservative and nonlinear, with a different
interaction law from FPUT and phi^4. Ground truth is generated by
Stormer-Verlet with many microsteps per saved coarse step.
"""
import json
import os
import time

import numpy as np
import torch


SAVE_DIR = "data/toda"
os.makedirs(SAVE_DIR, exist_ok=True)

N_PARTICLES = 32
DT = 0.05
H_GT = 0.001
SUBSTEPS = int(round(DT / H_GT))

N_TRAIN_STEPS = 500
N_TEST_STEPS = 20_000
N_MULTI_TEST_STEPS = 2_000
N_TRAIN_IC = 128
N_VAL_IC = 32
N_TEST_IC = 16
SEED = 20260411


def toda_force(q: np.ndarray) -> np.ndarray:
    return np.exp(np.roll(q, 1) - q) - np.exp(q - np.roll(q, -1))


def toda_hamiltonian(q: np.ndarray, p: np.ndarray) -> float:
    return float(0.5 * np.sum(p ** 2) + np.sum(np.exp(q - np.roll(q, -1))))


def stormer_verlet_step(q: np.ndarray, p: np.ndarray, h: float):
    p_half = p + 0.5 * h * toda_force(q)
    q_next = q + h * p_half
    p_next = p_half + 0.5 * h * toda_force(q_next)
    return q_next, p_next


def integrate(q0: np.ndarray, p0: np.ndarray, n_coarse: int, substeps: int):
    traj = np.empty((n_coarse + 1, 2 * N_PARTICLES), dtype=np.float64)
    traj[0] = np.concatenate([q0, p0])
    q = q0.copy()
    p = p0.copy()
    h_fine = DT / substeps
    for i in range(n_coarse):
        for _ in range(substeps):
            q, p = stormer_verlet_step(q, p, h_fine)
        traj[i + 1] = np.concatenate([q, p])
    return traj


def sample_initial_condition(rng: np.random.Generator, amp_range=(0.03, 0.12)):
    x = np.arange(N_PARTICLES)
    q = np.zeros(N_PARTICLES, dtype=np.float64)
    p = np.zeros(N_PARTICLES, dtype=np.float64)
    for k in (1, 2, 3):
        phase_q = rng.uniform(0.0, 2.0 * np.pi)
        phase_p = rng.uniform(0.0, 2.0 * np.pi)
        amp_q = rng.uniform(*amp_range) / k
        amp_p = rng.uniform(*amp_range) / k
        q += amp_q * np.sin(2.0 * np.pi * k * x / N_PARTICLES + phase_q)
        p += amp_p * np.cos(2.0 * np.pi * k * x / N_PARTICLES + phase_p)
    q -= q.mean()
    p -= p.mean()
    return q, p


def stack_trajectories(rng, n_ic, n_steps, label):
    out = []
    t0 = time.time()
    for i in range(n_ic):
        q0, p0 = sample_initial_condition(rng)
        out.append(integrate(q0, p0, n_steps, SUBSTEPS))
        if i == 0 or (i + 1) % 32 == 0 or i + 1 == n_ic:
            print(f"[toda] {label}: {i + 1}/{n_ic} trajectories")
    data = np.stack(out, axis=0)
    print(f"[toda] {label} done in {time.time() - t0:.1f}s; shape={data.shape}")
    return data


def sampled_max_relative_energy_error(traj, stride=100):
    flat = traj.reshape(-1, traj.shape[-1]) if traj.ndim == 3 else traj
    e0 = toda_hamiltonian(flat[0, :N_PARTICLES], flat[0, N_PARTICLES:])
    errs = []
    for state in flat[::stride]:
        e = toda_hamiltonian(state[:N_PARTICLES], state[N_PARTICLES:])
        errs.append(abs((e - e0) / (e0 + 1e-12)))
    return float(np.max(errs))


if __name__ == "__main__":
    rng = np.random.default_rng(SEED)

    train = stack_trajectories(rng, N_TRAIN_IC, N_TRAIN_STEPS, "train")
    val = stack_trajectories(rng, N_VAL_IC, N_TRAIN_STEPS, "val")
    test = stack_trajectories(rng, N_TEST_IC, N_MULTI_TEST_STEPS, "multi-test")

    q0_long, p0_long = sample_initial_condition(rng, amp_range=(0.05, 0.10))
    t0 = time.time()
    test_long = integrate(q0_long, p0_long, N_TEST_STEPS, SUBSTEPS)
    print(f"[toda] long test done in {time.time() - t0:.1f}s; shape={test_long.shape}")

    torch.save(torch.tensor(train, dtype=torch.float64), f"{SAVE_DIR}/train.pt")
    torch.save(torch.tensor(val, dtype=torch.float64), f"{SAVE_DIR}/val.pt")
    torch.save(torch.tensor(test, dtype=torch.float64), f"{SAVE_DIR}/test.pt")
    torch.save(torch.tensor(test_long, dtype=torch.float64), f"{SAVE_DIR}/test_long.pt")

    mean = train.reshape(-1, train.shape[-1]).mean(axis=0)
    std = train.reshape(-1, train.shape[-1]).std(axis=0) + 1e-12
    torch.save(torch.tensor(mean, dtype=torch.float64), f"{SAVE_DIR}/mean.pt")
    torch.save(torch.tensor(std, dtype=torch.float64), f"{SAVE_DIR}/std.pt")

    meta = {
        "system": "periodic_toda_lattice",
        "dim": 2 * N_PARTICLES,
        "n_particles": N_PARTICLES,
        "dt": DT,
        "h_gt": H_GT,
        "substeps": SUBSTEPS,
        "n_train_ic": N_TRAIN_IC,
        "n_val_ic": N_VAL_IC,
        "n_test_ic": N_TEST_IC,
        "n_train_steps": N_TRAIN_STEPS,
        "n_multi_test_steps": N_MULTI_TEST_STEPS,
        "n_test_long_steps": N_TEST_STEPS,
        "sampled_max_energy_error_test_long": sampled_max_relative_energy_error(test_long),
        "dtype": "float64",
    }
    with open(f"{SAVE_DIR}/meta.json", "w") as f:
        json.dump(meta, f, indent=2)

    print(f"[toda] Saved to {SAVE_DIR}/")
