"""
generate_phi4.py
----------------
Generate a one-dimensional phi^4 / nonlinear Klein-Gordon lattice.

Hamiltonian:
    H(q,p) = sum_j 0.5 p_j^2
           + 0.5 c^2 (q_{j+1} - q_j)^2
           + 0.5 omega0^2 q_j^2
           + 0.25 lam q_j^4

Periodic boundaries are used. Ground truth is generated by Stormer-Verlet with
many microsteps per saved coarse step.
"""
import json
import os
import time

import numpy as np
import torch


SAVE_DIR = "data/phi4"
os.makedirs(SAVE_DIR, exist_ok=True)

N_PARTICLES = 32
C_COUPLING = 1.0
OMEGA0 = 1.0
LAMBDA = 1.0

DT = 0.05
H_GT = 0.001
SUBSTEPS = int(round(DT / H_GT))

N_TRAIN_STEPS = 500
N_TEST_STEPS = 20_000
N_MULTI_TEST_STEPS = 2_000
N_TRAIN_IC = 128
N_VAL_IC = 32
N_TEST_IC = 16
SEED = 20260410


def phi4_force(q: np.ndarray) -> np.ndarray:
    lap = np.roll(q, -1) - 2.0 * q + np.roll(q, 1)
    return C_COUPLING ** 2 * lap - OMEGA0 ** 2 * q - LAMBDA * q ** 3


def phi4_hamiltonian(q: np.ndarray, p: np.ndarray) -> float:
    dq = np.roll(q, -1) - q
    kinetic = 0.5 * np.sum(p ** 2)
    coupling = 0.5 * C_COUPLING ** 2 * np.sum(dq ** 2)
    onsite = 0.5 * OMEGA0 ** 2 * np.sum(q ** 2)
    nonlinear = 0.25 * LAMBDA * np.sum(q ** 4)
    return float(kinetic + coupling + onsite + nonlinear)


def stormer_verlet_step(q: np.ndarray, p: np.ndarray, h: float):
    p_half = p + 0.5 * h * phi4_force(q)
    q_next = q + h * p_half
    p_next = p_half + 0.5 * h * phi4_force(q_next)
    return q_next, p_next


def integrate(q0: np.ndarray, p0: np.ndarray, n_coarse: int, substeps: int):
    traj = np.empty((n_coarse + 1, 2 * N_PARTICLES), dtype=np.float64)
    traj[0] = np.concatenate([q0, p0])
    q = q0.copy()
    p = p0.copy()
    h_fine = DT / substeps
    for i in range(n_coarse):
        for _ in range(substeps):
            q, p = stormer_verlet_step(q, p, h_fine)
        traj[i + 1] = np.concatenate([q, p])
    return traj


def sample_initial_condition(rng: np.random.Generator, amp_range=(0.10, 0.35)):
    x = np.arange(N_PARTICLES)
    q = np.zeros(N_PARTICLES, dtype=np.float64)
    for k in (1, 2, 3):
        amp = rng.uniform(*amp_range) / k
        phase = rng.uniform(0.0, 2.0 * np.pi)
        q += amp * np.sin(2.0 * np.pi * k * x / N_PARTICLES + phase)
    q += rng.normal(0.0, 0.02, size=N_PARTICLES)
    p = rng.normal(0.0, 0.04, size=N_PARTICLES)
    return q, p


def stack_trajectories(rng, n_ic, n_steps, label):
    out = []
    t0 = time.time()
    for i in range(n_ic):
        q0, p0 = sample_initial_condition(rng)
        out.append(integrate(q0, p0, n_steps, SUBSTEPS))
        if i == 0 or (i + 1) % 32 == 0 or i + 1 == n_ic:
            print(f"[phi4] {label}: {i + 1}/{n_ic} trajectories")
    data = np.stack(out, axis=0)
    print(f"[phi4] {label} done in {time.time() - t0:.1f}s; shape={data.shape}")
    return data


def max_relative_energy_error(traj):
    if traj.ndim == 3:
        flat = traj.reshape(-1, traj.shape[-1])
    else:
        flat = traj
    q0, p0 = flat[0, :N_PARTICLES], flat[0, N_PARTICLES:]
    e0 = phi4_hamiltonian(q0, p0)
    errors = []
    for state in flat[:: max(1, len(flat) // 2000)]:
        e = phi4_hamiltonian(state[:N_PARTICLES], state[N_PARTICLES:])
        errors.append(abs((e - e0) / (e0 + 1e-12)))
    return float(np.max(errors))


if __name__ == "__main__":
    rng = np.random.default_rng(SEED)

    train = stack_trajectories(rng, N_TRAIN_IC, N_TRAIN_STEPS, "train")
    val = stack_trajectories(rng, N_VAL_IC, N_TRAIN_STEPS, "val")
    test = stack_trajectories(rng, N_TEST_IC, N_MULTI_TEST_STEPS, "multi-test")

    q0_long, p0_long = sample_initial_condition(rng, amp_range=(0.18, 0.22))
    t0 = time.time()
    test_long = integrate(q0_long, p0_long, N_TEST_STEPS, SUBSTEPS)
    print(f"[phi4] long test done in {time.time() - t0:.1f}s; shape={test_long.shape}")

    torch.save(torch.tensor(train, dtype=torch.float64), f"{SAVE_DIR}/train.pt")
    torch.save(torch.tensor(val, dtype=torch.float64), f"{SAVE_DIR}/val.pt")
    torch.save(torch.tensor(test, dtype=torch.float64), f"{SAVE_DIR}/test.pt")
    torch.save(torch.tensor(test_long, dtype=torch.float64), f"{SAVE_DIR}/test_long.pt")

    meta = {
        "system": "phi4_klein_gordon_lattice",
        "dim": 2 * N_PARTICLES,
        "n_particles": N_PARTICLES,
        "dt": DT,
        "h_gt": H_GT,
        "substeps": SUBSTEPS,
        "c_coupling": C_COUPLING,
        "omega0": OMEGA0,
        "lambda": LAMBDA,
        "n_train_ic": N_TRAIN_IC,
        "n_val_ic": N_VAL_IC,
        "n_test_ic": N_TEST_IC,
        "n_train_steps": N_TRAIN_STEPS,
        "n_multi_test_steps": N_MULTI_TEST_STEPS,
        "n_test_long_steps": N_TEST_STEPS,
        "sampled_max_energy_error_test_long": max_relative_energy_error(test_long),
        "dtype": "float64",
    }
    with open(f"{SAVE_DIR}/meta.json", "w") as f:
        json.dump(meta, f, indent=2)

    mean = train.reshape(-1, train.shape[-1]).mean(axis=0)
    std = train.reshape(-1, train.shape[-1]).std(axis=0) + 1e-12
    torch.save(torch.tensor(mean, dtype=torch.float64), f"{SAVE_DIR}/mean.pt")
    torch.save(torch.tensor(std, dtype=torch.float64), f"{SAVE_DIR}/std.pt")

    print(f"[phi4] Saved to {SAVE_DIR}/")
